---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
    attributes:
      apt:
        compile_time_update: true
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[dnsimple::default]
    attributes:
