---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[dnsimple::default]
    attributes:
