---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: ubuntu-12.04
    attributes:
      apt:
        compile_time_update: true
  - name: centos-6.7

suites:
  - name: chef12
    provisioner:
      require_chef_omnibus: 12
    run_list:
      - recipe[dnsimple::default]
    attributes:

  - name: chef11
    provisioner:
      require_chef_omnibus: '11.18.12'
    run_list:
      - recipe[dnsimple::default]
    attributes:
