language: ruby
bundler_args: --without development integration
rvm:
  - 2.2
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
before_script:
  - bundle exec berks install
script: bundle exec rspec spec
notifications:
  slack:
    secure: lVBlbzgrccMTu6dEeTjfZd9s4Idg9A1S3IKKUpTMuwYXrfz76bU8t0AOCZUMHjZwEfVGW+YFwgIUgjpnJAxPz8Qp36pnKEbzXtX5lgqFmefUQEFmTXfQCT6M5Y0NXV0YLIFo6a1py0Jr4btCm6imV0UylPQpqolpNO7JOVFkMjk=
