language: ruby
rvm: 2.2
sudo: required
services: docker

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

install: echo "skip bundle install"

before_script:
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef gem install chefstyle

script: chef exec rake quick

notifications:
  slack:
    email: false
    secure: lVBlbzgrccMTu6dEeTjfZd9s4Idg9A1S3IKKUpTMuwYXrfz76bU8t0AOCZUMHjZwEfVGW+YFwgIUgjpnJAxPz8Qp36pnKEbzXtX5lgqFmefUQEFmTXfQCT6M5Y0NXV0YLIFo6a1py0Jr4btCm6imV0UylPQpqolpNO7JOVFkMjk=
